module:
  mounts:
    - source: archetypes
      target: archetypes
    - source: assets
      target: assets
    - source: content
      target: content
    - source: i18n
      target: i18n
    - source: layouts
      target: layouts

# Default
permalinks:
  persons_statutes: /team/statutes/:slug/
taxonomies:
  persons_status: persons_statutes
